spring:
  application.name: flowable-rest
  datasource:
    username: postgres
    password: echoshen
    url: jdbc:postgresql://10.0.0.2:5432/core-flowable-6.6
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
logging:
  level:
    root: error
    cn.adbyte: debug