# 参考：
# https://hub.docker.com/r/flowable/flowable-rest
# The Swagger docs will be available on
# http://localhost:8080/flowable-rest/docs

### 查看版本
GET http://{{host}}/management/engine
Authorization: Basic rest-admin test

### 部署资源
POST http://{{host}}/repository/deployments
Authorization: Basic rest-admin test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="holiday-request.bpmn20.xml"
Content-Type: text/xml

< holiday-request.bpmn20.xml
--WebAppBoundary

### 查询部署资源
GET http://{{host}}/repository/process-definitions
Authorization: Basic rest-admin test

### 启动流程实例
POST http://{{host}}/runtime/process-instances
Authorization: Basic rest-admin test
Content-Type: application/json

{
  "processDefinitionKey": "holidayRequest",
  "variables": [
    {
      "name": "employee",
      "value": "John Doe"
    },
    {
      "name": "nrOfHolidays",
      "value": 7
    }
  ]
}

### 查询流程实例列表
GET http://{{host}}/runtime/process-instances
Authorization: Basic rest-admin test
Content-Type: application/json

> {% client.global.set("processInstanceId", response.body.data[0].id); %}


### Get diagram for a process instance
GET http://{{host}}/runtime/process-instances/{{processInstanceId}}/diagram
Authorization: Basic rest-admin test

### 查询任务列表
POST http://{{host}}/query/tasks
Authorization: Basic rest-admin test
Content-Type: application/json

{ "candidateGroup" : "managers" }

> {% client.global.set("taskId", response.body.data[0].id); %}

### 为任务增加评论（可以不断增加）
POST http://{{host}}/runtime/tasks/{{taskId}}/comments
Authorization: Basic rest-admin test
Content-Type: application/json

{
  "message" : "{\"approve\":true,\"msg\":\"好\"}",
  "saveProcessInstanceId" : true
}
### 查询任务所有评论
GET http://{{host}}/runtime/tasks/{{taskId}}/comments
Authorization: Basic rest-admin test


### 为任务增加附件（可以不断增加）
POST http://{{host}}/runtime/tasks/{{taskId}}/attachments
Authorization: Basic rest-admin test
Content-Type: application/json

{
  "name":"附件名称是必填项 其它随意",
  "description":"Simple attachment description",
  "type":"simpleType",
  "externalUrl":"http://flowable.org"
}

### 查询任务所有附件
GET http://{{host}}/runtime/tasks/{{taskId}}/attachments
Authorization: Basic rest-admin test


### 查询任务所有历史事件
GET http://{{host}}/runtime/tasks/{{taskId}}/events

### 认领任务
POST http://{{host}}/runtime/tasks/{{taskId}}
Content-Type: application/json

{
  "action" : "claim",
  "assignee" : "userWhoClaims"
}

### 委托任务
POST http://{{host}}/runtime/tasks/{{taskId}}
Content-Type: application/json

{
  "action" : "delegate",
  "assignee" : "userToDelegateTo"
}

### 解决任务
POST http://{{host}}/runtime/tasks/{{taskId}}
Content-Type: application/json

{
  "action" : "resolve"
}

### 完成任务
### 必须把jar文件放入到lib下，REST才能找到对应的资源（cn.adbyte.flowable.a.CallExternalSystemDelegate）
POST http://{{host}}/runtime/tasks/{{taskId}}
Authorization: Basic rest-admin test
Content-Type: application/json

{ "action" : "complete", "variables" : [ { "name" : "approved", "value" : true} ]  }

### 查询历史任务实例 url 参数
GET http://{{host}}/history/historic-task-instances

### 查询历史任务实例 body 参数
POST http://{{host}}/query/historic-task-instances
Content-Type: application/json

{}